### ISSUE TITLE
Mac OS Support

### ISSUE THREAD

**Issue by tongclement** [jazonshou/HolonomicLib#22]
**State and describe your question**
It seems like the converter.exe mentioned in the "getting started guide - https://holonomiclibdocs.readthedocs.io/en/latest/Docs/Intro/GettingStarted.html " is an exe file - just curious, would it work on macOS? Many thanks!

**Comment by jazonshou** [comment]
Currently, it is not supported for macOS. But if you have python, you can download and run [convertor.py](https://github.com/jazonshou/HolonomicLib/blob/master/Pathplanner/deploy/pathplanner/convertor.py).
