### ISSUE TITLE
Installation: KeyError: "There is no item named 'template.pros' in the archive"

### ISSUE THREAD

**Issue by tongclement** [jazonshou/HolonomicLib#23]
**Describe the bug**
When running the command: `pros conductor fetch HolonomicLib@1.zip`, the error `KeyError: "There is no item named 'template.pros' in the archive"` occurred. I tried putting the `HolonomicLib@1.zip` file inside the src folder and in the root of the project (outside of src) but nothing changed. Any advice will be appreciated.

**To Reproduce**
https://holonomiclibdocs.readthedocs.io/en/latest/Docs/Intro/GettingStarted.html

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jazonshou** [comment]
Please keep the zip in the root of the project and run `pros conductor fetch HolonomicLib@1.0.2.zip`. Let me know if that fixes it

**Comment by tongclement** [comment]
worked - seemed like the problem was safari was unzipping the .zip file and the zip format changes if you re-compress it on Mac - just download as format in safari and save it as zip so it doesn't open and it worked. Will try out the library tomorrow - many thanks!
